name: My PR Test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'development'
    
jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Echo something
        run: echo 'Hello World'
        
  if_merged:
    if: github.event.pull_request.merged == true    
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
