name: My PR Test

on:
  pull_request:
    types:
      - opened
    branches:
      - 'development'
    
jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Echo something
        run: echo 'Hello World'
